definitions:
  model.Person:
    properties:
      address:
        type: string
      id:
        type: integer
      name:
        type: string
      uuid:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /person:
    get:
      consumes:
      - application/json
      description: get all person
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Person'
            type: array
      summary: Get All Person
      tags:
      - person
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
